# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oogiridojo', '0002_auto_20170918_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='free_vote_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
