# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oogiridojo', '0003_answer_free_vote_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odai_text', models.CharField(max_length=100)),
                ('example_text', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='odai',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oogiridojo.Odai'),
            preserve_default=False,
        ),
    ]
