# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oogiridojo', '0004_auto_20170923_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='odai',
            name='example_text',
            field=models.CharField(default='reirei', max_length=20),
            preserve_default=False,
        ),
    ]
