# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oogiridojo', '0005_odai_example_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odai',
            name='example_text',
            field=models.CharField(max_length=50),
        ),
    ]
