# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oogiridojo', '0005_tsukkomi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judgement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judgement_text', models.CharField(max_length=140)),
                ('judgement_score', models.PositiveIntegerField(default=0)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oogiridojo.Answer')),
            ],
        ),
    ]
