# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oogiridojo', '0006_judgement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgement',
            name='judgement_text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tsukkomi',
            name='tsukkomi_text',
            field=models.CharField(max_length=200),
        ),
    ]
