# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oogiridojo', '0007_auto_20171021_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date modified'),
        ),
    ]
