# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oogiridojo', '0008_answer_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(max_length=300),
        ),
    ]
