# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oogiridojo', '0011_article_practice'),
    ]

    operations = [
        migrations.AddField(
            model_name='monkasei',
            name='ningenryoku',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
