# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-03 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oogiridojo', '0013_answer_img_datauri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odai',
            name='odai_text',
            field=models.CharField(max_length=200),
        ),
    ]
