# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-24 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oogiridojo', '0014_auto_20180403_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='client_ip',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='monkasei',
            name='ningenryoku',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
